Project_v3/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Project_v3.Models;

namespace Project_v3.Controllers
{
    [Route("director")]
    [Authorize(Roles = "Moderator")]
    public class DirectorsController : Controller
    {
        private readonly AplicationDbContext _context;
        
        public DirectorsController(AplicationDbContext context)
        {
            _context = context;
        }

        // GET: Directors
        
        [HttpGet("index")]
        public async Task<IActionResult> Index()
        {
              return View(await _context.Directors.ToListAsync());
        }
        
        [HttpGet("details")]
        // GET: Directors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (director == null)
            {
                return NotFound();
            }

            return View(director);
        }
        
        [HttpGet("create")]
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Directors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDirector dir)
        {
            if (ModelState.IsValid)
            {
                Director dir1 = new Director()
                {
                    Name = dir.Name,
                    Surname = dir.surname,
                    fullname = $"{dir.Name} {dir.surname}"
                };
                _context.Add(dir1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        
        [HttpGet("edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors.FindAsync(id);
            if (director == null)
            {
                return NotFound();
            }
            EditDirector editdirector = new EditDirector()
            {
                Name = director.Name,
                Surname = director.Surname
            };

            return View(editdirector);
        }

        // POST: Directors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost("edit/{id}")]
        public async Task<IActionResult> Edit([FromRoute]int id, EditDirector director)
        {
            var check = _context.Directors.FirstOrDefault(x => x.Id == id);
            if (check == null)
            {
                return NotFound();
            }
            Director director2 = new Director()
            {
                Id = check.Id,
                Name = director.Name,
                Surname = director.Surname,
                fullname = check.fullname,
                Films = check.Films
            };
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Directors.Remove(check);
                    _context.Directors.Update(director2);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DirectorExists(director2.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }

        // GET: Directors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (director == null)
            {
                return NotFound();
            }

            return View(director);
        }

        // POST: Directors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Directors == null)
            {
                return Problem("Entity set 'AplicationDbContext.Directors'  is null.");
            }
            var director = await _context.Directors.FindAsync(id);
            if (director != null)
            {
                _context.Directors.Remove(director);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DirectorExists(int id)
        {
          return _context.Directors.Any(e => e.Id == id);
        }
    }
}

Project_v3/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Eventing.Reader;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project_v3.Models;

namespace Project_v3.Controllers
{
    [Authorize]
    [Route("films")]
    public class FilmsController : Controller
    {
        private UserManager<AppUser> _userManager;
        private readonly AplicationDbContext _context;

        public FilmsController(AplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [AllowAnonymous]
        [HttpGet("Index")]
        public ActionResult<IEnumerable<Films>> Index()
        {
            var result = _context.Films.Include(x => x.Director).Include(f => f.Users).ToList();

            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(int id)
        {
            var film = _context.Films.FirstOrDefault(o => o.Id == id);
            film.FilmCount++;
            _context.SaveChanges();

            return View();

        }

        // GET: Films/Details/5
        [AllowAnonymous]
        [HttpGet("details/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Films == null)
            {
                return NotFound();
            }

            var films = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (films == null)
            {
                return NotFound();
            }

            return View(films);
        }
        [Authorize(Roles = "User, Moderator")]
        public async Task<ActionResult> Rank(int id)
        {
            var film = _context.Films.Include(f => f.Users).FirstOrDefault(x => x.Id == id);
            var user = await _userManager.GetUserAsync(User);
            var user1 = _context.Users.Include(x => x.films).FirstOrDefault(f => f.Id == user.Id);
            if (film != null && user != null)
            {
                if (film.Users.IndexOf(user1) >= 0)
                {
                    film.Users.Remove(user1);
                    user1.films.Remove(film);
                    if (film.FilmCount > 0)
                    {
                        film.FilmCount--;
                    }
                }
                else
                {
                    user1.films.Add(film);
                    film.Users.Add(user1);
                    film.FilmCount++;
                }
            }
            else
            {
                return NotFound();
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet("ranking")]
        [AllowAnonymous]
        public ActionResult<IEnumerable<Films>> Ranking()
        {
            var result = _context.Films.Include(x => x.Director).OrderByDescending(s => s.FilmCount).ToList();
            return View(result);
        }

        [Authorize(Roles = "Moderator")]
        [HttpGet("create")]
        public IActionResult Create()
        {
            var list = _context.Directors.ToList();
            List<string> fullname = new List<string>();
            foreach (var item in list)
            {
                fullname.Add(item.fullname);
            }
            CreateFilm director = new CreateFilm()
            {
                FullNames = fullname
            };
            return View(director);
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Moderator")]
        [HttpPost("create")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(CreateFilm film)
        {

            var directors = _context.Directors.FirstOrDefault(x => x.fullname == film.selectedDirector);
            if (directors == null)
            {
                return NotFound();
            }
            Films Cfilm = new Films()
            {

                FilmName = film.FilmName,
                FilmDescription = film.FilmDescription,
                FilmType = film.FilmType,
                Directorfullname = directors.fullname,

            };
            Cfilm.Director = directors;
            _context.Add(Cfilm);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
        [Authorize(Roles = "Moderator")]
        [HttpGet("edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Films == null)
            {
                return NotFound();
            }

            var films = await _context.Films.FindAsync(id);
            if (films == null)
            {
                return NotFound();
            }
            EditFilm editfilm = new EditFilm()
            {
                FilmName = films.FilmName,
                FilmDescription = films.FilmDescription,
                FilmType = films.FilmType
            };
            return View(editfilm);
        }


        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Moderator")]
        [HttpPost("edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, EditFilm film)
        {
            var check = _context.Films.FirstOrDefault(x => x.Id == id);
            if (check == null)
            {
                return NotFound();
            }
            Films films = new Films()
            {
                Id = check.Id,
                FilmName = film.FilmName,
                FilmDescription = film.FilmDescription,
                FilmType = film.FilmType,
                FilmCount = check.FilmCount,
                Directorfullname = check.Directorfullname,
                Director = check.Director,
                Users = check.Users
            };
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Films.Remove(check);
                    _context.Films.Update(films);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmsExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }
        [Authorize(Roles = "Moderator")]
        [HttpGet("delete/{id}")]
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Films == null)
            {
                return NotFound();
            }

            var films = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (films == null)
            {
                return NotFound();
            }

            return View(films);
        }

        // POST: Films/Delete/5
        [Authorize(Roles = "Moderator")]
        [HttpPost("delete/{id}")]
        
        public async Task<IActionResult> Delete([FromRoute]int id)
        {
            if (_context.Films == null)
            {
                return Problem("Entity set 'AplicationDbContext.Films'  is null.");
            }
            var films = await _context.Films.FindAsync(id);
            if (films != null)
            {
                _context.Films.Remove(films);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool FilmsExists(int id)
        {
            return _context.Films.Any(e => e.Id == id);
        }
    }
}

Project_v3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Films</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project_v3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project_v3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Films" asp-action="Index">Films</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Films" asp-action="Ranking">Ranking</a>
                        </li>
                        @if(User.Identity.IsAuthenticated && User.IsInRole("Moderator")){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Directors" asp-action="Index">Directors</a>
                        </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Logout"> Wyloguj</a>
                            </li>
                        } else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Logowanie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Rejestracja</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Project_v3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>